def start():
    print('')
    print('███████╗██╗   ██╗███████╗███╗   ██╗████████╗   ██╗      █████╗ ██████╗') 
    print('██╔════╝██║   ██║██╔════╝████╗  ██║╚══██╔══╝   ██║     ██╔══██╗██╔══██╗')
    print('█████╗  ██║   ██║█████╗  ██╔██╗ ██║   ██║█████╗██║     ███████║██████╔╝')
    print('██╔══╝  ╚██╗ ██╔╝██╔══╝  ██║╚██╗██║   ██║╚════╝██║     ██╔══██║██╔══██╗')
    print('███████╗ ╚████╔╝ ███████╗██║ ╚████║   ██║      ███████╗██║  ██║██████╔╝')
    print('╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═══╝   ╚═╝      ╚══════╝╚═╝  ╚═╝╚═════╝ ')
    print('')
    print('Towards Standardized Evaluation of Neuromorphic Localization Methods')
    print('================================================')
    print('Adam D Hines*, Alejandro Fontan, Michael Milford, Tobias Fischer')
    print('QUT Centre for Robotics, 2 George St, Brisbane 4000, Australia')
    print('')
    print('*adam.hines@qut.edu.au')
    print('================================================')
    print('Version 0.1.1 - February 2026')
    print('')